name: auth
description: "A new Flutter package project."
version: 0.0.1
homepage:
environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"
dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  delightful_toast: ^1.1.0
  dio: ^5.8.0+1
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.7.0
  formz: ^0.8.0
  gap: ^3.0.1
  geolocator: ^13.0.2
  get_it: ^8.0.3
  http: ^1.2.2
  hydrated_bloc: ^10.0.0
  internet_connection_checker_plus: ^2.7.0
  intl: any
  json_annotation: ^4.9.0
  material_dialogs: ^1.1.4
  motion_toast: ^2.11.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  retrofit: ^4.0.3
  error:
    git:
      url: https://github.com/HishamKoptaN/error.git
      ref: main
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.5.7
  injectable_generator: ^2.3.0
  intl_utils: ^2.5.0
  json_serializable: ^6.7.1
  retrofit_generator: ">=8.0.0 <10.0.0"
  version_assist: ^1.3.4
  flutter_lints: ^5.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: "Tajawal"
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_images.dart
  field_prefix: null
flutter_intl:
  enabled: false
